{% set name = "libcuest" %}
{% set version = "0.1.1.1" %}
{% set cuda_compiler_version = cuda_compiler_version | default("None") %}
{% set abiversion = version.split('.')[0] %}
{% set majorminorpatch = '.'.join(version.split('.')[:3]) %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "sbsa-linux" %}  # [aarch64]
{% set extension = "tar.xz" %}  # [not win]

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuest/redist/{{ name }}/{{ platform }}/{{ name }}-{{ platform }}-{{ version }}_cuda12-archive.{{ extension }}  # [(cuda_compiler_version or "").startswith("12")]
  url: https://developer.download.nvidia.com/compute/cuest/redist/{{ name }}/{{ platform }}/{{ name }}-{{ platform }}-{{ version }}_cuda13-archive.{{ extension }}  # [(cuda_compiler_version or "").startswith("13")]
  sha256: 25e4b38ab3996c4c8ac5cbe372fce050eaa3a9cea1efd120165d78e735967c5b  # [linux64 and (cuda_compiler_version or "").startswith("12")]]
  sha256: 0a4dbaab73bf78d1a4a11ce0bc9f503fc70b0c24559c0e46d782f0fc688599ba  # [linux64 and (cuda_compiler_version or "").startswith("13")]]
  sha256: 8514f370bae8ada4d2d9b4ab461ad9fe0b61533b5b2a65c35a3ff97f9a919d50  # [linux and aarch64 and (cuda_compiler_version or "").startswith("12")]]
  sha256: a67893e5176d6cc840326af1f0d938d803ca7d353bde0d1e1c503f4050750360  # [linux and aarch64 and (cuda_compiler_version or "").startswith("13")]]

build:
  number: 1
  skip: true  # [not (linux64 or aarch64) or cuda_compiler_version in ("None", "")]

requirements:
  build:
    - cf-nvidia-tools 1.*  # [linux]

outputs:
  - name: libcuest
    build:
      # Ignore run_exports on cuda-version which we need to add to avoid hash collision as we have multiple CTK support
      ignore_run_exports:
        - cuda-version
      # cuda-version will take care of constraining versions for the following
      # and thus we should ignore the run exports from them which are more strict
      ignore_run_exports_from:
        - libcublas-dev
        - libcusolver-dev
        - libcusparse-dev
        - libnvjitlink-dev
    files:
      - lib/libcuest*.so.*
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ stdlib("c") }}
        - {{ compiler('cuda') }}
      host:
        - libcublas-dev
        - libcusolver-dev
        - libcusparse-dev
        - libnvjitlink-dev
        - cuda-version {{ cuda_compiler_version }}
      run:
        - libcublas
        - libcusolver
        - libcusparse
        - libnvjitlink
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
    test:
      commands:
        - test -f $PREFIX/lib/libcuest.so.{{ majorminorpatch }}
        - test -L $PREFIX/lib/libcuest.so.{{ abiversion }}

  - name: libcuest-dev
    build:
      ignore_run_exports:
        - cuda-version
      # Export libcuest for a consuming feedstock that needs libcuest-dev in their host: section
      # For this lib, the breaking changes occur at the minor version (until major version reaches 1)
      run_exports:
        - {{ pin_subpackage("libcuest", max_pin="x.x") }}
    files:
      - lib/libcuest*.so
      - include/
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ stdlib("c") }}
        - {{ compiler('cuda') }}
      host:
        - cuda-version {{ cuda_compiler_version }}
        - {{ pin_subpackage("libcuest", exact=True) }}
      run:
        - {{ pin_compatible("cuda-version", min_pin="x", max_pin="x") }}
        - {{ pin_subpackage("libcuest", exact=True) }}
    test:
      commands:
        - test -L $PREFIX/lib/libcuest.so
        - test -f $PREFIX/include/cuest.h
        - test -d $PREFIX/include/cuest

  - name: libcuest-static
    build:
      ignore_run_exports:
        - cuda-version
    files:
      - lib/libcuest_static.a
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ stdlib("c") }}
        - {{ compiler('cuda') }}
      host:
        - cuda-version {{ cuda_compiler_version }}
        - {{ pin_subpackage("libcuest-dev", exact=True) }}
      run:
        - {{ pin_compatible("cuda-version", min_pin="x", max_pin="x") }}
        - {{ pin_subpackage("libcuest-dev", exact=True) }}
    test:
      commands:
        - test -f $PREFIX/lib/libcuest_static.a

about:
  home: https://developer.nvidia.com/cuest
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_file: LICENSE
  license_url: https://docs.nvidia.com/cuda/cuest/latest/license.html
  summary: cuEST - GPU-powered electronic structure theory
  description: |
    Fast, GPU-powered components for electronic structure theory
  doc_url: https://docs.nvidia.com/cuda/cuest/

extra:
  feedstock-name: libcuest
  recipe-maintainers:
    - conda-forge/cuda
